### ISSUE TITLE
Demo

### ISSUE THREAD

**Issue by masterj7874** [luohongyin/EntST#1]
"I followed your instructions as closely as possible, but to no avail. Could you please provide more detailed guidance? Applying your instructions in practice is challenging. Thank you in advance for your continued support."

**Comment by luohongyin** [comment]
In principle you can run our code by simplying running the bash commands in the `read.me`. But if you encounter any problem, please feel free to post error messages.

**Comment by masterj7874** [comment]
Thanks a lot!

Jeri Suh

2023년 10월 25일 (수) 오전 10:05, Hongyin Luo ***@***.***>님이 작성:
